<template lang="pug">
#privacy
    h1 Privacy Policy
    
    br
    br
    
    p Last updated: January 08, 2024
    
    br
    
    p This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
    
    br
    
    p We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
    
    br

    h2 Interpretation and Definitions
    
    br
    
    h3 Interpretation
    
    br

    p The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
    
    br

    h3 Definitions
    
    br

    p For the purposes of this Privacy Policy:

    br

    ul
        li
            p
                strong Account 
                | means a unique account created for You to access our Service or parts of our Service.
        li
            p
                strong Affiliate 
                | means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
        li
            p
                strong Company 
                | (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to broadway Inc., broadway Inc. Headquarters: 2F Yohan House, 24, Seongmisan-ro, Mapo-gu, Seoul, 03997, Republic of Korea.
        li
            p
                strong Country 
                | refers to: South Korea
        li
            p
                strong Device 
                | means any device that can access the Service such as a computer, a cellphone or a digital tablet.
        li
            p
                strong Personal Data 
                | is any information that relates to an identified or identifiable individual.
        li
            p
                strong Service 
                | refers to the Website.
        li
            p
                strong Service Provider 
                | means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
        li
            p
                strong Usage Data 
                | refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
        li
            p
                strong Website 
                | refers to Skapi, accessible from 
                a(href="https://www.skapi.com" rel="external nofollow noopener" target="_blank") https://www.skapi.com
        li
            p
                strong You 
                | means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
    
    br

    h2 Collecting and Using Your Personal Data

    br

    h3 Types of Data Collected

    br

    h4 Personal Data

    br

    p While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:

    br

    ul
        li
            p Email address
        li
            p First name and last name
        li
            p Phone number
        li
            p Usage Data
    
    br
    
    h4 Usage Data

    br

    p Usage Data is collected automatically when using the Service.

    br

    p Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
    
    br
    
    p When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
    
    br
    
    p We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
    
    br
    
    h3 Use of Your Personal Data

    br

    p The Company may use Personal Data for the following purposes:

    br

    ul
        li
            p
                strong To provide and maintain our Service
                | , including to monitor the usage of our Service.
        li
            p
                strong To manage Your Account: 
                | to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
        li
            p
                strong For the performance of a contract: 
                | the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
        li
            p
                strong To contact You: 
                | To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
        li
            p
                strong To provide You 
                | with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
        li
            p
                strong To manage Your requests: 
                | To attend and manage Your requests to Us.
        li
            p
                strong For business transfers: 
                | We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
        li
            p
                strong For other purposes 
                | We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
    
    br

    p We may share Your personal information in the following situations:

    br

    ul
        li
            strong With Service Providers: 
            | We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
        li
            strong For business transfers: 
            | We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
        li
            strong With Affiliates: 
            | We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
        li
            strong With business partners: 
            | We may share Your information with Our business partners to offer You certain products, services or promotions.
        li
            strong With other users: 
            | when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
        li
            strong With Your consent 
            | : We may disclose Your personal information for any other purpose with Your consent.
 
    br

    h3 Retention of Your Personal Data
    
    br
    
    p The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
    
    br

    p The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.

    br

    h3 Transfer of Your Personal Data
    
    br
    
    p Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
    
    br
    
    p Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
    
    br
    
    p The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
    
    br
    
    h3 Delete Your Personal Data
    
    br
    
    p You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
    
    br
    
    p Our Service may give You the ability to delete certain information about You from within the Service.
    
    br
    
    p You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
    
    br
    
    p Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
    
    br
    
    h3 Disclosure of Your Personal Data
    
    br
    
    h4 Business Transactions
    
    br
    
    p If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
    
    br
    
    h4 Law enforcement
    
    br
    
    p Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
    
    br
    
    h4 Other legal requirements
    
    br
    
    p The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
    
    br
    
    ul
        li Comply with a legal obligation
        li Protect and defend the rights or property of the Company
        li Prevent or investigate possible wrongdoing in connection with the Service
        li Protect the personal safety of Users of the Service or the public
        li Protect against legal liability
    
    br
    
    h3 Security of Your Personal Data
    
    br
    
    p The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
    
    br
    
    h2 Children's Privacy
    
    br
    
    p We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from our servers.
    
    br
    
    p If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
    
    br
    
    h2 Links to Other Websites
    
    br
    
    p Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
    
    br
    
    p We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
    
    br
    
    h2 Changes to this Privacy Policy
    
    br
    
    p We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
    
    br
    
    p We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.
    
    br
    
    p You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
    
    br
    
    h2 Contact Us
    
    br
    
    p If you have any questions about this Privacy Policy, You can contact us:
    
    br
    
    ul
        li By email: dev@broadwayinc.com
</template>
<style lang="less" scoped>
#privacy {
    max-width: 1000px;
    margin: 0 auto;
    padding: 8px;
    box-sizing: border-box;
}

h1,
h2,
h3,
h4,
h5,
h6 {
    color: black;
    opacity: 0.77;
    font-weight: 500;
    line-height: calc(1em + 0.5rem);
}

h1 {
    font-size: 3em;
}

h2 {
    font-size: 1.33333333rem;
}

h3 {
    font-size: 1.16666667rem;
}

h4 {
    font-size: 1rem;
}

p {
    color: black;
    opacity: 0.8;
    font-size: 1rem;
    line-height: calc(1em + 0.5rem);
    font-weight: 400;
}

br {
    line-height: 1em;
}

ul {
    padding-left: 2rem;

    li {
        margin-bottom: 1.2rem;
        font-weight: 300;
    }
}
</style>